# Generated by Django 5.1.7 on 2025-04-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
